### ISSUE TITLE
Remote Cursor Selection (Line selection Error in Firefox)

### ISSUE THREAD

**Issue by kutiny** [yjs/y-codemirror#16]
> Please save me some time and use the following template. In 90% of all issues I can't reproduce the problem because I don't know what exactly you are doing, in which environment, or which y-* version is responsible. Just use the following template even if you think the problem is obvious.

**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
The bug that I am reporting is currently only in firefox (I tested it in chrome and it is working as expected).
When a remote user selects more than one line and the selection has "blank lines" (no characters in it) this specific line disappears in the remote editor (line superposition).

**To Reproduce**
1. Go to: [Demo](https://demos.yjs.dev/codemirror/codemirror.html)
2. Create 3 lines: the first one with any characters, the second one empty and the last one with any characters
3. Open the same page in another tab and select the three lines
4. In the first tab you will see that the second line has disappeared in the remote selection

**Expected behavior**
The blank line must keep in its place and not over the previous (or the next) line

**Screenshots**
![Image](https://i.imgur.com/pZEhdvP.png)

**Environment Information**
 - Browser: Firefox 85.0.2 (64-bit)
 - Yjs Versions: not apply (the problem is reproducible from the demo)

**Comment by dmonad** [comment]
Thanks, I fixed the issue in y-codemirror@2.1.1

**Comment by lampnik** [comment]
Hi, I'm seeing this issue still occurring in the demo on Firefox 95.0.1. Can be reproduced using the same steps in the OP on the demo site.

**Comment by theova** [comment]
I can reproduce this bug on Firefox 109.0.1 on Ubuntu 22.04 LTS.
